name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build project
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - run: dotnet build
    - name: Install browsers
      run: pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps
    - name: Run Chromium tests
      run: xvfb-run dotnet test GoogleMapsPlaywright.csproj /p:CollectCoverage=true /p:IncludeTestAssembly=true /p:CoverletOutputFormat=cobertura --settings=chromium.runsettings
    - name: Run Firefox tests
      run: xvfb-run dotnet test --settings=firefox.runsettings
    - name: Run WebKit tests
      run: xvfb-run dotnet test --settings=webkit.runsettings
    - name: Generate coverage
      uses: action-badges/cobertura-coverage-xml-badges@0.3.1
      with:
        file-name: coverage.svg
        badge-branch: badges
        github-token: '${{ secrets.MAPS_CI }}'
        coverage-file-name: /home/runner/work/google-maps-playwright/google-maps-playwright/coverage.cobertura.xml
